### PR TITLE
Chore : for use waitFor in constructor

### PR DESCRIPTION
**Pull request by souricevincent**
waitFor function in constructor component

## Description
I add waitFor in new instance of component for use that in constructor

## Motivation and Context
To be connected with mithril's class documentation. By using classes, I prefer to do without opinait and use the constructor to declare my variables and to be able to use the useStrict mode of typescript.

## How Has This Been Tested?
nom run test => ok

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [X ] My code follows the code style of this project.
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.
- [X ] I have read all applicable contributing documents.
- [X ] I have added tests to cover my changes.
- [X ] All new and existing tests passed.
- [X ] I have updated the change log (if applicable).

### CODE REVIEW

**Comment by souricevincent** [comment]
Hello ! 👋
@isiahmeadows @StephanHoyer it's ok for you ? thk's

**Comment by souricevincent** [comment]
@StephanHoyer you still maintain this repository ?

**Comment by isiahmeadows** [comment]
What's the impetus for the change other than "nice to have"?

**Comment by souricevincent** [comment]
Hello, To get closer to what is documented here [https://github.com/MithrilJS/mithril.d.ts#classcomponent](mithril.d.ts).
It say : " // The constructor can be used in place of oninit" However, this is not possible if you want to give him the `waitFor`.

**Pull request closed without merging**
